/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import WindowsListener.IrAlMenu;
import persona.Persona;
import utilidades.Utilidades;

/**
 *
 * @author baquiax
 */
public class IngresoDeDatos extends javax.swing.JFrame {

    PantallaPrincipal principal;

    /**
     * Creates new form IngresoDeDatos
     *
     * @param principal
     * @param datos
     */
    public IngresoDeDatos(PantallaPrincipal principal, String datos) {
        initComponents();
        this.principal = principal;
        jtxtADatos.setText(datos);
        IrAlMenu irAlMenu = new IrAlMenu(this.principal, this);
        super.addWindowListener(irAlMenu);

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtADatos = new javax.swing.JTextArea();
        btnFinalizarApuesta = new javax.swing.JButton();
        jblTitulo = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ingreso de Apuestas");

        jtxtADatos.setColumns(20);
        jtxtADatos.setRows(5);
        jScrollPane1.setViewportView(jtxtADatos);

        btnFinalizarApuesta.setText("Finalizar Apuestas");
        btnFinalizarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarApuestaActionPerformed(evt);
            }
        });

        jblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("Ingreso de Apuestas");

        lblFormato.setText("Nombre,Apuesta,1ero,2do,3ro,4to,5to,6to,7mo,8vo,9no,10mo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnFinalizarApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormato)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTitulo)
                .addGap(25, 25, 25)
                .addComponent(lblFormato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarApuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarApuestaActionPerformed
        // TODO add your handling code here:
        String apuesta = jtxtADatos.getText();
        String apuestas[] = apuesta.split("\n");
        int contador = 0;
        for (int i = 0; i < apuestas.length; i++) {
            String aux[] = apuestas[i].split(",");
            if (aux.length == 12) {
                int[] caballos = new int[10];
                for (int j = 0; j < caballos.length; j++) {
                    caballos[j] = Integer.valueOf(aux[j + 2]);
                }
                if (Utilidades.repetidos(caballos)) {
                    contador++;
                }
            }
        }
        Persona apuestasValidas[] = new Persona[contador];
        String apuestasInvalidas[] = new String[apuestas.length - contador];
        int index = 0;
        int index2 = 0;
        for (int i = 0; i < apuestas.length; i++) {
            String aux[] = apuestas[i].split(",");
            if (aux.length == 12) {
                int[] caballos = new int[10];
                for (int j = 0; j < caballos.length; j++) {
                    caballos[j] = Integer.valueOf(aux[j + 2]);
                }
                if (Utilidades.repetidos(caballos)) {
                    Persona auxPersona = new Persona(aux[0], 0, Integer.valueOf(aux[1]), caballos);
                    apuestasValidas[index] = auxPersona;
                    index++;
                } else {
                    apuestasInvalidas[index2] = apuestas[i];
                    index2++;
                }
            } else {
                apuestasInvalidas[index2] = apuestas[i];
                index2++;
            }
        }
        System.out.println("Apuestas validas");
        for (int i = 0; i < apuestasValidas.length; i++) {
            System.out.println(apuestasValidas[i].toString());
        }
        System.out.println("Apuestas Invalidas");
        for (int i = 0; i < apuestasInvalidas.length; i++) {
            System.out.println(apuestasInvalidas[i]);
        }
    }//GEN-LAST:event_btnFinalizarApuestaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarApuesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JTextArea jtxtADatos;
    private javax.swing.JLabel lblFormato;
    // End of variables declaration//GEN-END:variables
}
